apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
      - name: backend-ventas
        # 🔥 URI interna de su repositorio ECR para Ventas
        image: 816051012141.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_ENDPOINT
          value: "URL_DE_SU_BASE_DE_DATOS_RDS" # <- Reemplazar por su RDS real
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "tu_base_datos"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "tu_password"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ventas-service
  namespace: default
spec:
  selector:
    app: backend-ventas
  ports:
  - protocol: TCP
    port: 80         # Puerto interno del clúster
    targetPort: 8080 # Redirige al contenedor
  type: ClusterIP # 🔥 Protegido dentro de la red privada
