apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despacho
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-despacho
  template:
    metadata:
      labels:
        app: backend-despacho
    spec:
      containers:
      - name: backend-despacho
        image: bencasolocaso/backend-despacho:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        # ¡Aquí reinyectamos las variables vitales para que conecte con su BD!
        - name: DB_ENDPOINT
          value: "${{ secrets.DB_ENDPOINT }}" # O la URL de su RDS directamente si no usan secrets para esto
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "tu_base_datos"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "tu_password"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-despacho-service
  namespace: default
spec:
  selector:
    app: backend-despacho
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
