apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
      - name: backend-ventas
        image: bencasolocaso/backend-ventas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ventas-service
  namespace: default
spec:
  selector:
    app: backend-ventas
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
