apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-despacho
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-despacho
  template:
    metadata:
      labels:
        app: frontend-despacho
    spec:
      containers:
      - name: frontend-despacho
        image: bencasolocaso/frontend-despacho:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # ¡Bloque de resources eliminado con éxito para liberar las cuotas!
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-despacho-service
  namespace: default
spec:
  selector:
    app: frontend-despacho
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
