apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-despacho
  namespace: default
spec:
  replicas: 2 # Duplicado para alta disponibilidad como pide la pauta
  selector:
    matchLabels:
      app: frontend-despacho
  template:
    metadata:
      labels:
        app: frontend-despacho
    spec:
      containers:
      - name: frontend-despacho
        # 🔥 URI interna de su ECR para el Front
        image: 816051012141.dkr.ecr.us-east-1.amazonaws.com/front-despacho:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # Puerto en el que corre el servidor web (Nginx/Apache) del Front
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-despacho-service
  namespace: default
spec:
  selector:
    app: frontend-despacho
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer # 🔥 Crea el balanceador de AWS conectado a las subredes públicas
